services:
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: cyberSafe
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/cyberSafe_backup.sql:/docker-entrypoint-initdb.d/cyberSafe_backup.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1G'
    networks:
      - cybersafe

  backend:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    container_name: backend
    environment:
      DB_USER: postgres
      DB_PASSWORD: myPassword
      DB_NAME: cyberSafe
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - cybersafe
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1G'

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1G'

networks:
  cybersafe:
    driver: bridge

volumes:
  db-data:
